import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Script from 'next/script'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Denkyu Sinar Abadi - Stabilizer, Transformer & Battery Charger Specialist',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <head>
                <meta charset="UTF-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
                <style>{`
                    .nav-link {
                        position: relative;
                    }
                    .nav-link::after {
                        content: '';
                        position: absolute;
                        width: 0;
                        height: 2px;
                        bottom: -2px;
                        left: 0;
                        background-color: #2563eb;
                        transition: width 0.3s ease;
                    }
                    .nav-link:hover::after {
                        width: 100%;
                    }
                    .hero {
                        background: linear-gradient(135deg, #f8fafc 0%, #e0f2fe 100%);
                    }
                    .product-card:hover {
                        transform: translateY(-5px);
                        box-shadow: 0 10px 25px rgba(37, 99, 235, 0.2);
                    }
                    .product-card {
                        transition: all 0.3s ease;
                    }
                    .hamburger {
                        transition: all 0.3s ease;
                    }
                    .hamburger.active .hamburger-line:nth-child(1) {
                        transform: translateY(8px) rotate(45deg);
                    }
                    .hamburger.active .hamburger-line:nth-child(2) {
                        opacity: 0;
                    }
                    .hamburger.active .hamburger-line:nth-child(3) {
                        transform: translateY(-8px) rotate(-45deg);
                    }
                    .mobile-menu {
                        max-height: 0;
                        overflow: hidden;
                        transition: max-height 0.3s ease-out;
                    }
                    .mobile-menu.open {
                        max-height: 500px;
                    }
                    .feature-icon {
                        background: linear-gradient(135deg, #3b82f6 0%, #2563eb 100%);
                    }
                `}</style>
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans bg-white text-gray-800`}
            >
                <header className="sticky top-0 z-50 bg-white shadow-md">
                    <div className="container mx-auto px-4 py-3">
                        <div className="flex justify-between items-center">
                            <div className="flex items-center">
                                <a href="#" className="flex items-center">
                                    <div className="w-10 h-10 bg-blue-600 rounded-full flex items-center justify-center text-white font-bold text-xl mr-2">DSA</div>
                                    <span className="text-xl font-bold text-blue-600">Denkyu Sinar Abadi</span>
                                </a>
                            </div>

                            <nav className="hidden md:flex space-x-8">
                                <a href="#home" className="nav-link text-gray-700 hover:text-blue-600 font-medium">Home</a>
                                <a href="#products" className="nav-link text-gray-700 hover:text-blue-600 font-medium">Products</a>
                                <a href="#about" className="nav-link text-gray-700 hover:text-blue-600 font-medium">About</a>
                                <a href="#services" className="nav-link text-gray-700 hover:text-blue-600 font-medium">Services</a>
                                <a href="#contact" className="nav-link text-gray-700 hover:text-blue-600 font-medium">Contact</a>
                            </nav>

                            <div className="md:hidden">
                                <button id="hamburger" className="hamburger focus:outline-none">
                                    <div className="hamburger-line w-6 h-0.5 bg-gray-700 mb-1.5 transition-all duration-300"></div>
                                    <div className="hamburger-line w-6 h-0.5 bg-gray-700 mb-1.5 transition-all duration-300"></div>
                                    <div className="hamburger-line w-6 h-0.5 bg-gray-700 transition-all duration-300"></div>
                                </button>
                            </div>
                        </div>

                        <div id="mobileMenu" className="mobile-menu md:hidden bg-white">
                            <div className="flex flex-col space-y-3 py-4 px-4">
                                <a href="#home" className="nav-link text-gray-700 hover:text-blue-600 font-medium">Home</a>
                                <a href="#products" className="nav-link text-gray-700 hover:text-blue-600 font-medium">Products</a>
                                <a href="#about" className="nav-link text-gray-700 hover:text-blue-600 font-medium">About</a>
                                <a href="#services" className="nav-link text-gray-700 hover:text-blue-600 font-medium">Services</a>
                                <a href="#contact" className="nav-link text-gray-700 hover:text-blue-600 font-medium">Contact</a>
                            </div>
                        </div>
                    </div>
                </header>
                <main>{children}</main>
                <Script src="/script.js" />
            </body>
        </html>
    )
}
